services:

  # Flask application container
  flask_app:
    build: .
    container_name: flask_chat_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis_db
      - mysql_db
    restart: unless-stopped

  # Redis container for message queue and caching
  redis_db:
    image: redis:alpine
    container_name: redis_chat_db
    volumes:
      - redis_data:/data
    restart: unless-stopped
    ports:
      - "6379:6379"

  # MySQL container for persistent relational storage
  mysql_db:
    image: mysql:8.0
    container_name: mysql_chat_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"

# Persistent storage volumes for Redis and MySQL
volumes:
  redis_data:
  mysql_data:
